#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0
mkdir 0.02
cp -rf 0.org/* 0.02

runApplication blockMesh

runApplication decomposePar -force

unzip bodiesInfo.zip

application=`getApplication`

runParallel $application &