#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# prepare boundary conditions
rm -rf 0
cp -r 0.org 0

# prepare parafoam file
paraFoam -touch
paraFoam -builtin -touch

# create mesh
runApplication blockMesh

# prepare application
application=`getApplication`

# run application
runApplication $application

