#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

cp -r 0.org 0

paraFoam -touch

runApplication blockMesh
runApplication decomposePar -force

#runApplication surfaceFeatureExtract

#runApplication snappyHexMesh -overwrite

application=`getApplication`

# runApplication $application

runParallel $application
#~ 
#~ runParallel reconstructParMesh
#~ 
runApplication reconstructPar -newTimes

postProcess -func 'patchAverage(name=top,wallShearStress)'

# ----------------------------------------------------------------- end-of-file
