#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0
mkdir 0.005
cp -rf 0.org/* 0.005

unzip bodiesInfo.zip

runApplication blockMesh

runApplication decomposePar -force

application=`getApplication`
runParallel $application &
paraFoam -touch
