for (label level=0;level<maxRefinementLevel+1;level++)
{
    mesh.update();

    if (mesh.changing())
    {
        // Do not apply previous time-step mesh compression flux
        // if the mesh topology changed
        if (mesh.topoChanging())
        {
            talphaPhi1Corr0.clear();
        }

        gh = (g & mesh.C()) - ghRef;
        ghf = (g & mesh.Cf()) - ghRef;

        MRF.update();

        if (correctPhi)
        {
            // Calculate absolute flux
            // from the mapped surface velocity
            phi = mesh.Sf() & Uf();

            #include "correctPhi.H"

            // Make the flux relative to the mesh motion
            fvc::makeRelative(phi, U);

            mixture.correct();
        }

        if (checkMeshCourantNo)
        {
            #include "meshCourantNo.H"
        }

        lambda *= 0.0;
        HFDIBDEM.recreateBodies(lambda,refineF);
    }
}
